name: Update dist/

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"

jobs:
  update_dist:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "Workflow - Dist Update"
          git config --global user.email "--"
          git fetch
          git checkout dist-updates || git checkout -b dist-updates
          git reset --hard origin/main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build dist/
        run: npm run build

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Setup GitHub CLI
        if: env.changes_detected == 'true'
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Commit and create Pull Request
        if: env.changes_detected == 'true'
        run: |
          git add dist/
          git commit -m "Update dist files"
          git push -f origin dist-updates
          gh pr list --head dist-updates | grep dist-updates || gh pr create --base main --head dist-updates --title "Update dist files" --body "This PR updates the dist files after dependency updates." --label "automated-pr"
